### ISSUE TITLE
请问Gradle同步的时候报错了,麻烦帮个忙看看

### ISSUE THREAD

**Issue by leonzhao** [dongorigin/AndroidDemo#1]
signingConfigs {
        release {
            storeFile file(STOREFILE)
            storePassword STOREPASSWORD
            keyAlias KEYALIAS
            keyPassword KEYPASSWORD
        }
    }

Error:(28, 0) Could not get unknown property 'STOREFILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null} of type com.android.build.gradle.internal.dsl.SigningConfig.
<a href="openFile:/home/leon/AndroidStudioProjects/AndroidDemo/app/build.gradle">Open File</a>

**Comment by dongorigin** [comment]
找不到的这几个配置是我的本地配置。你可以暂时先移除signingConfigs与其使用，这样就可以编译通过了。我之后再把Gradle的配置优化一下，保证在其他机器上可以跑。

**Comment by liverloop** [comment]
我也出现了这种错误

**Comment by dongorigin** [comment]
实在抱歉，我尽快修复这个错误

**Comment by dongorigin** [comment]
已修复此问题，不再强制依赖本地全局gradle配置，一直没有处理这个问题实在是万分抱歉
